### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by TheRemiDev** [ShadowChi1d/CloudNet-PlaceholderAPI#1]
[14:36:50] [Server thread/ERROR]: Could not load 'plugins/RaidersPlaceholders-1.0.1-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/clip/placeholderapi/expansion/PlaceholderExpansion
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[paper.jar:git-Paper-773]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[paper.jar:git-Paper-773]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [paper.jar:git-Paper-773]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:292) [paper.jar:git-Paper-773]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:204) [paper.jar:git-Paper-773]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:573) [paper.jar:git-Paper-773]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NoClassDefFoundError: me/clip/placeholderapi/expansion/PlaceholderExpansion
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_252]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_252]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_252]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_252]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_252]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_252]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_252]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paper.jar:git-Paper-773]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paper.jar:git-Paper-773]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[paper.jar:git-Paper-773]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[paper.jar:git-Paper-773]
	... 6 more
Caused by: java.lang.ClassNotFoundException: me.clip.placeholderapi.expansion.PlaceholderExpansion
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paper.jar:git-Paper-773]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paper.jar:git-Paper-773]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_252]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_252]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_252]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_252]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_252]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_252]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_252]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[paper.jar:git-Paper-773]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[paper.jar:git-Paper-773]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_252]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_252]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_252]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_252]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[paper.jar:git-Paper-773]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[paper.jar:git-Paper-773]
	... 6 more

**Comment by ShadowChi1d** [comment]
Have you got PlaceholderAPI installed? Have you put the jar into the expansions folder?
